{
  "hash": "c2de7e455a2a72defb391f6228876659",
  "result": {
    "markdown": "---\ntitle: Una variable categórica\neditor:\n    render-on-save: true\n---\n\n\nEn este apartado se describen los métodos básicos para explorar y analizar una variable categórica. \n\nAnalizaremos en concreto la variable `species` de nuestra hoja de datos, para conocer la distribución de los pingüinos por especies.\n\nComenzamos seleccionando la variable de interés en nuestra hoja de datos. Almacenamos el resultado en un nuevo objeto de nombre `species`. \n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\nspecies = penguins[\"species\"]\n```\n:::\n\n\n## El método `describe()` {#sec-1categorical-describe}\n\nPara obtener la información más relevante sobre la distribución de las especies de pingüinos aplicamos a `species` el método `describe()`:\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\nspecies.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\ncount        344\nunique         3\ntop       Adelie\nfreq         152\nName: species, dtype: object\n```\n:::\n:::\n\n\nDe la salida anterior obtenemos la siguiente información sobre la variable `species`:\n\nFragmento de la salida | Significado\n----- | -------\n`count   344`  | Hay $344$ valores no nulos, así que se conoce la especie de todos los pingüinos del estudio.\n`unique    3`  | La variable toma tres valores diferentes, es decir, hay tres categorías (las tres especies Adelie, Chinstrap y Gentto).\n`top  Adelie` | La categoría `top` o más frecuente, es decir, la especie más numerosa es la especie Adelie.\n`freq    152` | El número de pingüinos de la especie Adelie (la categoría `top`) es $152$.\n\n\n:::{#exr-1categorical-describe}\nUtiliza el método `describe()` para obtener información sobre la distribución de los pingüinos por islas.\n:::\n\n## Tabla de recuentos {#sec-value-counts}\n\nYa sabemos que la especie más numerosa es Adelie, con $152$ pingüinos, pero aún no sabemos cuántos pingüinos hay de las otras dos especies, Chinstrap y Gentoo. Para obtener una tabla con el número de pingüinos de cada especie usamos la función `value_counts()`:\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\nspecies.value_counts()\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\nAdelie       152\nGentoo       124\nChinstrap     68\nName: species, dtype: int64\n```\n:::\n:::\n\n\nAhora sabemos que la segunda especie más numerosa es Gentoo, con 124 ejemplares, y que solo hay 68 pingüinos de la especie Chinstrap. \n\n\n\n::: {#exr-1categorial-sex-counts}\nDetermina el número total de hembras y de machos. \n:::\n\n\n\n## Diagrama de recuentos \n\n\nUn __diagrama de recuentos__ asocia a cada categoría una barra de longitud igual al número de observaciones en esa categoría. \n\nPara realizar un diagrama del recuento de pingüinos por especie usamos la función `countplot()` del paquete `seaborn`\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\nsns.countplot(data=penguins, x=\"species\");\n```\n\n::: {.cell-output .cell-output-display}\n![](1categorical_files/figure-html/cell-6-output-1.png){width=593 height=429}\n:::\n:::\n\n\n::: {.callout-note}\nSi quitas el punto y coma `;` al final de la instrucción anterior aparecerá el mensaje \n\n`<AxesSubplot:xlabel='count', ylabel='species'>` \n\nen la salida antes del gráfico. \n\nAl terminar una instrucción con punto y coma `;` se inhibe la impresión de la salida.\n:::\n\nNota que las alturas de las barras en el gráfico anterior coindicen con los recuentos que hemos calculado en el apartado anterior con `value_counts()`.\n\nA veces es preferible usar barras horizontales, porque se tiene más especio para las etiquetas de las categorías. \n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\nsns.countplot(data=penguins, y=\"species\");\n```\n\n::: {.cell-output .cell-output-display}\n![](1categorical_files/figure-html/cell-7-output-1.png){width=632 height=429}\n:::\n:::\n\n\n::: {.callout-note}\nPara realizar un diagrama de recuentos de las categorías de una variable categórica, usa la función `countplot()` de`seaborn`. E indica:\n\n- El nombre de la hoja de datos como valor del argumento `data`.\n- El nombre de la variable categórica como valor del argumento `x` si quieres barras verticales, o como valor del argumento `y` si quieres barras horizontales.\n:::\n\n\n\n::: {#exr-1categorial-countplot-vertical}\nCrea un diagrama de recuentos para el número de hembras y machos, con barras verticales.\n:::\n\n\n::: {#exr-1categorial-sns-countplot}\nCrea un diagrama de recuentos para el número de pingüinos en cada isla, con barras horizontales.\n:::\n\n\n\n## Personalización de los gráficos (opcional)\n\nLos gráficos de la librería `seaborn` admiten muchas opciones para personalizar su aspecto cambiando por ejemplo los colores, los rótulos de los ejes, etc.\n\nLa personalización de los gráficos no carece de importancia, siendo especialmente relevante dar títulos descriptivos a los ejes. Pero en esta práctica nos centraremos en los procedimientos para realizar los gráficos y en la mayoría de ocasiones omitiremos los detalles de personalización de los mismos, que pueden consultarse en la documentación de `seaborn`. \n\nEn este apartado se da una muestra de las opciones para personalizar los diagramas de recuentos que se han presentado en el apartado anterior. Se trata de un apartado opcional y puedes por ahora omitir su lectura y volver a él al final de la sesión. \n\n### Colores\n\n\nSi quieres un mismo color para todas las barras usa en argumento `color`:\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\nsns.countplot(data=penguins, x=\"species\", color=\"steelblue\");\n```\n\n::: {.cell-output .cell-output-display}\n![](1categorical_files/figure-html/cell-8-output-1.png){width=593 height=429}\n:::\n:::\n\n\nPuedes ver los colores disponibles [aquí](https://matplotlib.org/stable/tutorials/colors/colors.html).\n\nTambién se puede indicar una secuencia de colores usando el argumento `palette`:\n\n::: {.cell execution_count=8}\n``` {.python .cell-code}\nsns.countplot(data=penguins, x=\"species\", palette=[\"steelblue\", \"coral\", \"gold\"]);\n```\n\n::: {.cell-output .cell-output-display}\n![](1categorical_files/figure-html/cell-9-output-1.png){width=593 height=429}\n:::\n:::\n\n\nComo valor para `palette` se puede indicar una lista de colores, como en el ejemplo anterior, o el nombre de una de las paletes predefinidas (`deep`, `muted`, `pastel`, `bright`, `dark` y `colorblind`), como en el siguiente ejemplo:\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\nsns.countplot(data=penguins, x=\"species\", palette=\"colorblind\");\n```\n:::\n\n\n### Rótulos\n\nCon el siguiente código personalizamos los títulos de los ejes y damos un título global al gráfico\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\nax = sns.countplot(data=penguins, x=\"species\")\nax.set(\n    title=\"Número de pingüinos de cada especie\",\n    xlabel=\"Especie\", \n    ylabel=\"Número de pingüinos\"\n);\n```\n\n::: {.cell-output .cell-output-display}\n![](1categorical_files/figure-html/cell-11-output-1.png){width=594 height=450 fig-align='center'}\n:::\n:::\n\n\n### Orden de los niveles\n\nSi te fijas en los gráficos que has hecho hasta ahora, apreciarás que las categorías aparecen en los gráficos en el mismo orden en el que aparecen en las filas de la hoja de datos. \n\nSi quieres un orden personalizado para las categorías puedes usar el argumento `order`, como en el siguiente ejemplo:\n\n::: {.cell execution_count=11}\n``` {.python .cell-code}\nsns.countplot(data=penguins, x=\"species\", order = ['Chinstrap', 'Adelie', 'Gentoo']);\n```\n\n::: {.cell-output .cell-output-display}\n![](1categorical_files/figure-html/cell-12-output-1.png){width=593 height=429}\n:::\n:::\n\n\nCon el siguiente código ordenamos las categorías de mayor a menor frecuencia. \n\n::: {.cell execution_count=12}\n``` {.python .cell-code}\nsns.countplot(data=penguins, x=\"species\", order = species.value_counts().index);\n```\n\n::: {.cell-output .cell-output-display}\n![](1categorical_files/figure-html/cell-13-output-1.png){width=593 height=429}\n:::\n:::\n\n\n",
    "supporting": [
      "1categorical_files"
    ],
    "filters": [],
    "includes": {}
  }
}